version: '3.7'
services:
  latex:
    container_name: latex
    build: .
    volumes:
      # required
      - .:/root/texmf/tex/latex
      # change lines below if necessary
      - ../fha-sto:/mnt/fha-num1/
      - ../fha-swt:/mnt/fha-kosy/
      - ../fha-db:/mnt/fha-weit/
      - ../matse-spicker:/mnt/matse-spicker/
    tty: true
    restart: always
