version: '3.7'
services:
  latex:
    container_name: latex
    image: pblan/latex
    volumes:
      # required
      - .:/root/texmf/tex/latex
      # change lines below if necessary
      - ../fha-sto:/mnt/fha-sto/
      - ../fha-swt:/mnt/fha-swt/
      - ../fha-db:/mnt/fha-db/
      - ../matse-spicker:/mnt/matse-spicker/
    tty: true
    restart: always